name: CI

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
        default: '1.0.0'

jobs:
  build-and-test-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'

      - name: Run All Unit Tests
        run: go test ./...
      
      - name: Perform All Builds
        run: ./build.sh
      